import type { Metadata } from "next";
import { Geist } from "next/font/google";
import localFont from "next/font/local";
import ".././globals.css";

/* ===== Sans Font (زي ما هو) ===== */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

/* ===== Liberation Mono (Local) ===== */
const liberationMono = localFont({
  src: [
    {
      path: "../../public/fonts/LiberationMono-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/LiberationMono-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-liberation-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Taskly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${liberationMono.variable} h-full antialiased`}
    >
      <body className="min-h-full bg-background">{children}</body>
    </html>
  );
}
